name       : perl-uri
version    : '5.12'
release    : 15
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.12.tar.gz : 66abe0eaddd76b74801ecd28ec1411605887550fc0a45ef6aa744fdad768d9b3
homepage   : https://metacpan.org/pod/URI
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : URI - Uniform Resource Identifiers (absolute and relative)
description: |
    This module implements the URI class. Objects of this class represent "Uniform Resource Identifier references" as specified in RFC 2396 (and updated by RFC 2732). A Uniform Resource Identifier is a compact string of characters that identifies an abstract or physical resource. A Uniform Resource Identifier can be further classified as either a Uniform Resource Locator (URL) or a Uniform Resource Name (URN). The distinction between URL and URN does not matter to the URI class interface. A "URI-reference" is a URI that may have additional information attached in the form of a fragment identifier.
builddeps  :
    - perl-test-needs
    - perl-business-isbn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
