name       : perl-uri
version    : 1.71
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/URI-1.71.tar.gz : 9c8eca0d7f39e74bbc14706293e653b699238eeb1a7690cc9c136fb8c2644115
license    :
    - Artistic-Perl-1.0
summary    : Perl URI class module
component  : programming.perl
description: |
    This module implements the URI class. Objects of this class represent "Uniform Resource Identifier references" as specified in RFC 2396 (and updated by RFC 2732). A Uniform Resource Identifier is a compact string of characters that identifies an abstract or physical resource. A Uniform Resource Identifier can be further classified as either a Uniform Resource Locator (URL) or a Uniform Resource Name (URN). The distinction between URL and URN does not matter to the URI class interface. A "URI-reference" is a URI that may have additional information attached in the form of a fragment identifier.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
