name       : perl-uri
version    : '1.74'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz : a9c254f45f89cb1dd946b689dfe433095404532a4543bdaab0b71ce0fdcdd53d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl URI class module
description: |
    This module implements the URI class. Objects of this class represent "Uniform Resource Identifier references" as specified in RFC 2396 (and updated by RFC 2732). A Uniform Resource Identifier is a compact string of characters that identifies an abstract or physical resource. A Uniform Resource Identifier can be further classified as either a Uniform Resource Locator (URL) or a Uniform Resource Name (URN). The distinction between URL and URN does not matter to the URI class interface. A "URI-reference" is a URI that may have additional information attached in the form of a fragment identifier.
builddeps  :
    - perl-test-needs
    - perl-business-isbn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
